### ISSUE TITLE
01 installation: 

### ISSUE THREAD

**Issue by ngoiyaeric** [OpenInterpreter/01#278]
**Describe the bug**
Cannot install:
running poetry install says it cannot install torch 2.3.0 
torch 2.2.2 is already installed 

**To Reproduce**
1. python 3.9 - 3.12 

  - Installing torch (2.3.0): Failed

  RuntimeError

  Unable to find installation candidates for torch (2.3.0)

  at ~/.pyenv/versions/3.9.18/lib/python3.9/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install torch.

**Expected behavior**
Running poetry run 01 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/karibu/.pyenv/versions/3.9.18/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/karibu/Desktop/01-main/software/start.py", line 1, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
**Screenshots**
<img width="625" alt="Screen Shot 2024-05-24 at 1 16 36 PM" src="https://github.com/OpenInterpreter/01/assets/115367894/b6785bf5-dcf2-497a-8aa6-7899ab5fd887">

**Desktop (please complete the following information):**
 - OS: [mac OS: Monterey]
 - Python Version [e.g. 22]

**Additional context**

**Comment by alam234** [comment]
I have the same issue as this, just now. Can anybody assist on this?
OS : Mac Sonoma 14.5
Python : 3.10

**Comment by 0xrushi** [comment]
Try `pip install typer`

**Comment by sbouden** [comment]
I have the same issue with :
OS: Mac Sonoma 14.4 
Python: 3.12.2
When I run poetry add torch or torchvision, it fails:

```
 - Installing torch (2.3.1): Failed

  RuntimeError

  Unable to find installation candidates for torch (2.3.1)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install torch.
```

**Comment by stevenjryall1029384756** [comment]
I'm also having this problem with Mac OS Sonoma 14.5, Mac Mini 2018. Perhaps an issue with Intel CPUs?

**Comment by sgjohnson1981** [comment]
If I'm putting this here in error someone let me know. Looks like this user is getting two errors that may or may not be related. If I need to open my own issue, someone feel free to let me know.

I'm getting the typer error in Windows 10 (though not the torch error). If I run `poetry show --tree` I see that typer is a dependency of fastapi-cli which is a dependency of fastapi which is a dependency of open-interpreter. When I run just `poetry show` it says typer is already installed. So not sure how to go forward here.

**Comment by soliblue** [comment]
are there any updates on this? i am having the same issue on macbook pro (2021) with m1 pro chip

**Comment by MikeBirdTech** [comment]
Just a reminder that Open Interpreter requires Python 3.10 or 3.11. There are multiple posts in this thread with invalid versions of Python.

If you're using the correct version of Python, please include more information about your setup to help with debugging

**Comment by sbouden** [comment]
Hello,
The solution for me was to change to torch==2.2.2 otherwise it wouldn't
work.

Good luck !
Sonia
