### ISSUE TITLE
RealTimeSTT asyncio error on startup

### ISSUE THREAD

**Issue by rjcoupe** [OpenInterpreter/01#286]
**Describe the bug**
On startup, the application successfully opens the websocket and records input, but never seems to do anything with it. An error regarding RealtimeSTT is visible earlier in the logging output.

**To Reproduce**
Install as described in this guide with Python 3.11.9 available, run `poetry run 01` to start.

**Expected behavior**
Application starts up as described in documentation.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - Python Version [e.g. 22] 3.11.9

**Additional context**
```
❯ poetry run 01
The currently activated Python version 3.12.3 is not supported by the project (>=3.9,<3.12).
Trying to find and use a compatible version.
Using python3 (3.11.9)
[2024-06-28 11:21:54.760] [ctranslate2] [thread 24649577] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
[nltk_data] Downloading package punkt to /Users/richard/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
Starting server on 0.0.0.0:10001
INFO:     Started server process [16955]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
RealTimeSTT: asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Device.play_audiosegments() done, defined at /Users/richard/personal/01/software/source/clients/base_device.py:153> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/Users/richard/personal/01/software/source/clients/base_device.py", line 157, in play_audiosegments
    mpv_process = subprocess.Popen(
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mpv'
INFO:     Uvicorn running on http://0.0.0.0:10001 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 51248) - "WebSocket /" [accepted]
INFO:     connection open

Hold the spacebar to start recording. Press CTRL-C to exit.
                 Recording started...
Recording stopped.
```

**Comment by virtuman** [comment]
same issue

**Comment by GanQiao1990** [comment]
same

**Comment by AReid987** [comment]
this may be a python 3.11 issue. I don't know if open interpreter support python 3.12.x yet, but I am going to try to do a build of Open Interpreter with 3.12 and swap poetry for uv.
